import './globals.css'
import { Inter } from 'next/font/google'
import Header from '@/components/layout/header'
import Providers from '@/app/providers'
import Footer from '@/components/layout/footer'

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body>
        <div className="site-container">
          <Providers>
            <Header />
            <main>
              {children}
            </main>
            <Footer />
          </Providers>
        </div>
      </body>
    </html>
  )
}
