/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.3 /Users/oleg/Own/junction/tammerverse/public/models/6axis-robotic-arm.glb --transform --types -D
*/

import * as THREE from 'three'
import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'
import { GLTF } from 'three-stdlib'

type GLTFResult = GLTF & {
  nodes: {
    Cube: THREE.Mesh
    Cube_part: THREE.Mesh
    Bottom_fastener: THREE.Mesh
    Generator_stand: THREE.Mesh
    Arm_stand: THREE.Mesh
    Bottom_screw: THREE.Mesh
    Stand: THREE.Mesh
    Twisting_fastener: THREE.Mesh
    Twisting_fastener_base: THREE.Mesh
    Twisting_fastener_top: THREE.Mesh
    Mechanism: THREE.Mesh
    Fastening_arm_part: THREE.Mesh
    Genertor_base: THREE.Mesh
    ['FL57STH41-2804A002']: THREE.Mesh
    ['FL57STH41-2804A004']: THREE.Mesh
    ['E32-C42_光纤传感器011']: THREE.Mesh
    ['内六角圆柱头螺钉M2．5×6008']: THREE.Mesh
    大手臂右侧板002: THREE.Mesh
    大手臂支杆002: THREE.Mesh
    大手臂旋转轴_002: THREE.Mesh
    大手臂驱动轴承座005: THREE.Mesh
    ['深沟球轴承6204-2Z010']: THREE.Mesh
    ['深沟球轴承6204-2Z011']: THREE.Mesh
    ['深沟球轴承6204-2Z015']: THREE.Mesh
    ['GB／T276-94深沟球轴承61803-2RZ002']: THREE.Mesh
    ['GB／T276-94深沟球轴承61803-2RZ004']: THREE.Mesh
    电机4架连接轴A002: THREE.Mesh
    同步带2002: THREE.Mesh
  }
  materials: {
    Material: THREE.MeshStandardMaterial
    Cube_part_material: THREE.MeshStandardMaterial
    Bottom_fastener_material: THREE.MeshStandardMaterial
    Generator_stand_material: THREE.MeshStandardMaterial
    Arm_stand_material: THREE.MeshStandardMaterial
    Bottom_screw_material: THREE.MeshStandardMaterial
    Stand_material: THREE.MeshStandardMaterial
    Twisting_fastener_material: THREE.MeshStandardMaterial
    Twisting_fastener_base_material: THREE.MeshStandardMaterial
    Twisting_fastener_top_material: THREE.MeshStandardMaterial
    Mechanism_material: THREE.MeshStandardMaterial
    Fastening_arm_part_material: THREE.MeshStandardMaterial
    Generator_base_material: THREE.MeshStandardMaterial
    ['Paint Metallic Black #1 #2 #1.002']: THREE.MeshStandardMaterial
    ['Titanium Rough #1.011']: THREE.MeshStandardMaterial
    ['Hard Rough Plastic Black #1.003']: THREE.MeshStandardMaterial
    ['内六角圆柱头螺钉M2．5×6:color:128:128:128.002']: THREE.MeshStandardMaterial
    ['Paint Matte Black #2.002']: THREE.MeshStandardMaterial
    ['Metal Rough White #1.006']: THREE.MeshStandardMaterial
    ['Metal Rough Black #2']: THREE.MeshStandardMaterial
    ['Paint Matte Yellow #1.001']: THREE.MeshStandardMaterial
    ['深沟球轴承6204-2Z:color:192:192:192.001']: THREE.MeshStandardMaterial
    ['深沟球轴承6204-2Z:color:170:134:66.001']: THREE.MeshStandardMaterial
    ['深沟球轴承6204-2Z:color:158:128:54.001']: THREE.MeshStandardMaterial
    ['GB／T276-94深沟球轴承61803-2RZ:cast carbon steel:_70e7728']: THREE.MeshStandardMaterial
    ['GB／T276-94深沟球轴承61803-2RZ:color:222:231:235']: THREE.MeshStandardMaterial
    ['电机4架连接轴A:satin finish aluminum:221:232:255']: THREE.MeshStandardMaterial
    ['Cardboard Box #1']: THREE.MeshStandardMaterial
  }
}

export function Model(props: JSX.IntrinsicElements['group']) {
  const { nodes, materials } = useGLTF('/models/6axis-robotic-arm-transformed.glb') as GLTFResult
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.Cube.geometry} material={materials.Material} />
      <mesh geometry={nodes.Cube_part.geometry} material={materials.Cube_part_material} rotation={[Math.PI / 2, 0, 0]} scale={0.01} />
      <mesh geometry={nodes.Bottom_fastener.geometry} material={materials.Bottom_fastener_material} rotation={[Math.PI / 2, 0, 0]} scale={0.01} />
      <mesh geometry={nodes.Generator_stand.geometry} material={materials.Generator_stand_material} rotation={[Math.PI / 2, 0, 0]} scale={0.01} />
      <mesh geometry={nodes.Arm_stand.geometry} material={materials.Arm_stand_material} rotation={[Math.PI / 2, 0, 0]} scale={0.01} />
      <mesh geometry={nodes.Bottom_screw.geometry} material={materials.Bottom_screw_material} rotation={[Math.PI / 2, 0, 0]} scale={0.01} />
      <mesh geometry={nodes.Stand.geometry} material={materials.Stand_material} rotation={[Math.PI / 2, 0, 0]} scale={0.01} />
      <mesh geometry={nodes.Twisting_fastener.geometry} material={materials.Twisting_fastener_material} rotation={[Math.PI / 2, 0, 0]} scale={0.01} />
      <mesh geometry={nodes.Twisting_fastener_base.geometry} material={materials.Twisting_fastener_base_material} rotation={[Math.PI / 2, 0, 0]} scale={0.01} />
      <mesh geometry={nodes.Twisting_fastener_top.geometry} material={materials.Twisting_fastener_top_material} rotation={[Math.PI / 2, 0, 0]} scale={0.01} />
      <mesh geometry={nodes.Mechanism.geometry} material={materials.Mechanism_material} rotation={[Math.PI / 2, 0, 0]} scale={0.01} />
      <mesh geometry={nodes.Fastening_arm_part.geometry} material={materials.Fastening_arm_part_material} rotation={[Math.PI / 2, 0, 0]} scale={0.01} />
      <mesh geometry={nodes.Genertor_base.geometry} material={materials.Generator_base_material} rotation={[Math.PI / 2, 0, 0]} scale={0.01} />
      <mesh geometry={nodes['FL57STH41-2804A002'].geometry} material={materials['Paint Metallic Black #1 #2 #1.002']} position={[0.065, 0.459, 0.018]} rotation={[Math.PI / 2, 0, Math.PI / 2]} scale={0.001} />
      <mesh geometry={nodes['FL57STH41-2804A004'].geometry} material={materials['Titanium Rough #1.011']} position={[0.065, 0.459, 0.018]} rotation={[Math.PI / 2, 0, Math.PI / 2]} scale={0.001} />
      <mesh geometry={nodes['E32-C42_光纤传感器011'].geometry} material={materials['Hard Rough Plastic Black #1.003']} position={[0.07, 0.241, -0.062]} rotation={[Math.PI / 2, -1.253, 0]} scale={0.001} />
      <mesh geometry={nodes['内六角圆柱头螺钉M2．5×6008'].geometry} material={materials['内六角圆柱头螺钉M2．5×6:color:128:128:128.002']} position={[0.074, 0.237, -0.044]} rotation={[0.128, -0.371, 1.912]} scale={0.001} />
      <mesh geometry={nodes.大手臂右侧板002.geometry} material={materials['Paint Matte Black #2.002']} position={[0.065, 0.331, -0.061]} rotation={[Math.PI / 2, 0, Math.PI]} scale={0.001} />
      <mesh geometry={nodes.大手臂支杆002.geometry} material={materials['Metal Rough White #1.006']} position={[0.097, 0.288, 0.055]} scale={0.001} />
      <mesh geometry={nodes.大手臂旋转轴_002.geometry} material={materials['Metal Rough Black #2']} position={[0.065, 0.203, 0.063]} rotation={[Math.PI / 2, 0, Math.PI / 2]} scale={0.001} />
      <mesh geometry={nodes.大手臂驱动轴承座005.geometry} material={materials['Paint Matte Yellow #1.001']} position={[0.065, 0.203, 0.095]} rotation={[Math.PI / 2, 0, -Math.PI / 2]} scale={0.001} />
      <mesh geometry={nodes['深沟球轴承6204-2Z010'].geometry} material={materials['深沟球轴承6204-2Z:color:192:192:192.001']} position={[0.065, 0.203, 0.081]} rotation={[-Math.PI / 2, 0, -Math.PI / 2]} scale={0.001} />
      <mesh geometry={nodes['深沟球轴承6204-2Z011'].geometry} material={materials['深沟球轴承6204-2Z:color:170:134:66.001']} position={[0.065, 0.203, 0.081]} rotation={[-Math.PI / 2, 0, -Math.PI / 2]} scale={0.001} />
      <mesh geometry={nodes['深沟球轴承6204-2Z015'].geometry} material={materials['深沟球轴承6204-2Z:color:158:128:54.001']} position={[0.065, 0.203, 0.081]} rotation={[-Math.PI / 2, 0, -Math.PI / 2]} scale={0.001} />
      <mesh geometry={nodes['GB／T276-94深沟球轴承61803-2RZ002'].geometry} material={materials['GB／T276-94深沟球轴承61803-2RZ:cast carbon steel:_70e7728']} position={[0.027, 0.539, 0]} rotation={[Math.PI / 2, 0, 0]} scale={0.001} />
      <mesh geometry={nodes['GB／T276-94深沟球轴承61803-2RZ004'].geometry} material={materials['GB／T276-94深沟球轴承61803-2RZ:color:222:231:235']} position={[0.027, 0.539, 0]} rotation={[Math.PI / 2, 0, 0]} scale={0.001} />
      <mesh geometry={nodes.电机4架连接轴A002.geometry} material={materials['电机4架连接轴A:satin finish aluminum:221:232:255']} position={[0.016, 0.539, 0]} rotation={[Math.PI / 2, -Math.PI / 2, 0]} scale={0.001} />
      <mesh geometry={nodes.同步带2002.geometry} material={materials['Cardboard Box #1']} position={[-0.234, 0.539, -0.042]} rotation={[Math.PI / 2, 0, Math.PI / 2]} scale={0.001} />
    </group>
  )
}

useGLTF.preload('/models/6axis-robotic-arm-transformed.glb')
